# Generated by Django 3.1.7 on 2021-03-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('Usuario', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=50)),
                ('senha2', models.CharField(max_length=50)),
            ],
        ),
    ]
