# Generated by Django 3.1.7 on 2021-03-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210323_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='senha2',
        ),
    ]
