# Generated by Django 3.1.7 on 2021-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.CharField(default='S', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='ativo',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='contato',
            name='procedimento',
            field=models.ManyToManyField(to='contatos.Procedimento'),
        ),
    ]
